server:
  port: 8090

spring:
  application:
    name: meeting-assistant
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  kafka:
#    bootstrap-servers: 127.0.0.1:9092
#    producer:
#      retries: 1
#      batch-size: 16384
#      buffer-memory: 1024000
#      acks: all
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
